FROM jenkins/jenkins:lts
ENV RUBY_VERSION 2.4.1

USER root
RUN apt-get --quiet --yes update
RUN curl -#LO https://rvm.io/mpapis.asc && gpg --import mpapis.asc
RUN \curl -sSL https://get.rvm.io | bash -s stable --ruby

RUN usermod -a -G rvm jenkins
USER jenkins
RUN /bin/bash -lc  "rvm install $RUBY_VERSION && rvm use $RUBY_VERSION --default"
RUN echo "gem: --no-rdoc --no-ri" >> ~/.gemrc
RUN /bin/bash -lc  "gem install bundler --no-doc --no-ri"
